// Type to category mapping
export const typeToCategory: { [key: string]: string } = {
  "Assault Rifle": "Weapon",
  "Battle Rifle": "Weapon",
  "Hand Cannon": "Weapon",
  LMG: "Weapon",
  Pistol: "Weapon",
  SMG: "Weapon",
  Shotgun: "Weapon",
  "Sniper Rifle": "Weapon",
  "Modification-Grip": "Modification",
  "Modification-Light-Mag": "Modification",
  "Modification-Medium-Mag": "Modification",
  "Modification-Muzzle": "Modification",
  "Modification-Shotgun-Mag": "Modification",
  "Modification-Shotgun-Muzzle": "Modification",
  "Modification-Stock": "Modification",
  "Modification-Tech-Mod": "Modification",
  "Quick Use-Gadget": "Quick Use",
  "Quick Use-Grenade": "Quick Use",
  "Quick Use-Regen": "Quick Use",
  "Quick Use-Trap": "Quick Use",
  "Quick Use-Utility": "Quick Use",
  "Advanced Material": "Loots",
  "Basic Material": "Loots",
  Key: "Loots",
  Misc: "Loots",
  Nature: "Loots",
  Recyclable: "Loots",
  "Refined Material": "Loots",
  Special: "Weapon",
  "Topside Material": "Loots",
  Trinket: "Loots",
  Augment: "Equipment",
  Shield: "Equipment",
  Ammo: "Equipment",
};

export const allCategories = [
  "Special",
  "Weapon",
  "Modification",
  "Quick Use",
  "Equipment",
  "Loots",
];

export const specialTypeLabels: { [key: string]: string } = {
  workshop_upgrade: "Workshop Upgrade",
  expedition: "Expedition",
  candlelight: "Candlelight",
  safe_to_recycle: "Safe to Recycle",
  crafting_material: "Crafting Material",
  quest: "Quest",
  scrappy: "Scrappy",
};
